### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by calibrae** [ssenart/gazpar2haws#45]
Hi ! I'm trying to setup your integration, and failing miserably.

Usually i'm writing conf into configuration.yaml for the main hass, and I was wondering if the correct one is 

```
logging:
  file: log/gazpar2haws.log
  console: true
  level: debug
  format: '%(asctime)s %(levelname)s [%(name)s] %(message)s'

grdf:
  scan_interval: 0 # Number of minutes between each data retrieval (0 means no scan: a single data retrieval at startup, then stops).
  devices:
  - name: gazpar2haws # Name of the device in home assistant. It will be used as the entity_ids: sensor.${name}_volume and sensor.${name}_energy.
    username: "!secret grdf.username"
    password: "!secret grdf.password"
    pce_identifier: "!secret grdf.pce_identifier"
    timezone: Europe/Paris
    last_days: 365 # Number of days of data to retrieve
    reset: false # If true, the data will be reset before the first data retrieval

homeassistant:
  host: "!secret homeassistant.host"
  port: "!secret homeassistant.port"
  token: "!secret homeassistant.token"
```
 or 

```
grdf:
    scan_interval: 480
    username:
    password:
    pce_identifier:
    timezone: Europe/Paris
    last_days: 365
    reset: false 
```

Thanks for your help, cheers.
