### ISSUE TITLE
no entities created

### ISSUE THREAD

**Issue by sysam68** [ssenart/gazpar2haws#54]
Hi,

I have installed gazpar2haws add-on home assistant VM.

> Core 2025.1.2
> Supervisor 2024.12.3
> Operating System 14.1
> Interface utilisateur 20250109.0

Configuration of gazpar : 
```
grdf:
  scan_interval: 480
  username: <mylogin>
  password: <mypasswd>
  pce_identifier: <mypce>
  timezone: europe/paris
  last_days: 730 --> want a maximum of history, also tried with 1, 10, 365 value with same result.
  reset: true
```

According to the log, everything is fine 👍 

> 2025-01-18 10:10:17,755 DEBUG [gazpar2haws.haws] Importing 727 statistics for sensor.gazpar2haws_energy from recorder...
> 2025-01-18 10:10:17,756 DEBUG [gazpar2haws.haws] Sending a message...
> 2025-01-18 10:10:17,759 DEBUG [websockets.client] > TEXT '{"type": "recorder/import_statistics", "metadat...03999999999}], "id": 5}' [66560 bytes]
> 2025-01-18 10:10:17,777 DEBUG [websockets.client] < TEXT '{"id":5,"type":"result","success":true,"result":null}' [53 bytes]
> 2025-01-18 10:10:17,778 DEBUG [gazpar2haws.haws] Received response
> 2025-01-18 10:10:17,778 DEBUG [gazpar2haws.haws] Imported 727 statistics for sensor.gazpar2haws_energy from recorder
> 2025-01-18 10:10:17,779 INFO [gazpar2haws.bridge] Device 'gazpar2haws' data published to Home Assistant WS.
> 2025-01-18 10:10:17,779 INFO [gazpar2haws.bridge] Gazpar data published to Home Assistant WS.
> 2025-01-18 10:10:17,779 DEBUG [gazpar2haws.haws] Disconnecting from Home Assistant...

Checking at developer-tools/statistics, no gazpar sensor available.
Checking enities I have the following : 

> Pourcentage de mémoire sensor.gazpar2haws_pourcentage_de_memoire
> Pourcentage du processeur sensor.gazpar2haws_pourcentage_du_processeur
> Version sensor.gazpar2haws_version
> Version la plus récente sensor.gazpar2haws_version_la_plus_recente

In the energy configuration page, I can see sensor.gazpar2haws_energy and sensor.gazpar2haws_volume. Selecting one is possible, then the second disappear. A message "entities not defined, check your integration" is shown.

No value data for the sensor.

How are the entities created by the add-on ?
Is the add-on dependant from an another integration to create first the relevant entity / sensors ?
